export const cities = [
    {
        id: 'city1',
        url: 'https://images.app.goo.gl/oCJk8srGiDzReicMA',
        title: 'Indian Institute Of Technology',
        state: 'Maharashtra',
        city: 'Bombay',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Internationally IIT Bombay is ranked 149 by the QS World University Rankings 2024 under the Top Global Universities category and 172 in the QS World Rankings 2023. IIT Bombay offers degree and dual degree programmes at the UG PG and doctorate levels. The institute offers 80+ courses under 16 departments in the stream of Engineering Technology Science and Management. The applicants are chosen through national-level tests conducted by various authorities such as JEE Advanced GATE etc.',
    },
    {
        id: 'city2',
        url: 'https://images.app.goo.gl/wb3gR6WYb1qne8DT6',
        title: 'Visvesvaraya National Institute Of Technology',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Visvesvaraya National Institute of Technology Nagpur formally known as Visvesvaraya Regional College of Engineering is a public technical university located in the city of Nagpur Maharashtra. Established in 1960 the institute is among 31 National Institutes of Technology in the country',
    },
    {
        id: 'city3',
        url: 'https://images.app.goo.gl/iW6Rd7eUFomiqZNy6',
        title: 'College Of Engineering',
        state: 'Maharashtra',
        city: 'PUNE',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'COEP Pune was established in 1854 and now is known as COEP Technological University. Located in Pune the unitary public university of the government of Maharashtra through 14 departments offers UG PG and PhD courses to students. These courses are provided across Management Planning and various other streams. The university is accredited by the NBA and is ranked 73 by NIRF 2023 under the Engineering category.',
    },
    {
        id: 'city4',
        url: 'https://images.app.goo.gl/N767cdsFB87G3MPq9',
        title: 'Bharati Vidyapeeth Deemed University College Of Engineering',
        state: 'Maharashtra',
        city: 'PUNE',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'The College ranked 99th for Engineering by NIRF 2020 and 93rd for Private Engineering by NIRF 2019.It comprises 11 departments to impart education and knowledge in Civil Engineering Chemical Engineering Computer Engineering Information Technology Electrical Engineering Electronics Engineering Mechanical Engineering Production Engineering Basic Science and Humanities E and TC Engineering and Computer Science and Business Systems.',
    },
    {
        id: 'city5',
        url: 'https://images.app.goo.gl/SVCh25STiv7BzVya8',
        title: 'Vishwakarma Institute Of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vishwakarma Institute of Technology is an AICTE-approved private institute for higher education in Pune Maharashtra established in 1983. It offers various courses including Ph.D MCA B.E. / B.Tech M.E./M.Tech in the 2 streams (Engineering IT & Software). Students can occupy their seats out of a total of 1464 seats available and pursue various popular courses with a specialisation in Chemical Engineering Electronics Engineering Computer Science Engineering Power Engineering Information Technology Industrial Engineering Mechanical Engineering Artificial Intelligence & Machine Learning Telecommunication Engineering Instrumentation Technology Production Engineering.',
    },
    {
        id: 'city6',
        url: 'https://images.app.goo.gl/wYMPnH6sBaeawJnP9',
        title: 'University Institute Of Chemical Technology',
        state: 'Maharashtra',
        city: 'Jalgaon',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'UICT (University Institute of Chemical Technology) of Kavayitri Bahinabai Chaudhari North Maharashtra University founded in the year 1994 (formerly known as University Department of Chemical Technology) caters to the academic research technical and entrepreneurial needs in the field of Plastics/Paint/Oil/Food and Chemical Engineering and has now established itself as centre of academic excellence. Prof. J. B. Naik is heading the Institute. The Institute offers AICTE recognized Bachelor of Technology (B. Tech.) and Master of Technology (M. Tech.) degree courses and pursues Ph. D. Research Programme in Chemical Engineering and Technology Chemistry and Environmental Sciences. The curricula of all the courses are designed as per the emerging requirement of Industries.',
    },
    {
        id: 'city7',
        url: 'https://images.app.goo.gl/9BpdN6B2JN7R2GcE8',
        title: 'Kasegaon Education Societys Rajarambapu Institute Of Technology',
        state: 'Maharashtra',
        city: 'Islampur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Kasegaon Education Societys Rajarambapu Institute Of Technology Isunaided - Private Institute Located At Islampur Inmaharashtra . It Operates Under The Parent Organization Kasegaon Education Society . The Institute Started Its First Course In 1992. Kasegaon Education Societys Rajarambapu Institute Of Technology Is Open For Both Men And Women.',
    },
    {
        id: 'city8',
        url: 'https://images.app.goo.gl/vi2k8ot5csELtNBT6',
        title: 'Veermata Jijabai Technological Institute',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'VJTI Mumbaihas pioneered India’s Engineering education research and training ecosystem. In 1997 VJTI changed its name to Veermata Jijabai Technological Institute to honor mother of Chhatrapati Shivaji Maharaj. The institute offers programs in engineering and technology at the diploma degree post-graduate and doctoral levels. VJTI is known for its high quality teaching collaborative research industry connect and strong alumni network.',
    },
    {
        id: 'city9',
        url: 'https://images.app.goo.gl/vi2k8ot5csELtNBT6',
        title: 'Rajarambapu Institute of Technology',
        state: 'Maharashtra',
        city: 'Rajaramnagar',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Secured the “Rank/Band of 101-150” in the “NIRF INNOVATION RANKING 2023” by NIRF Ministry of Education Government of India (earlier known as “ARIIA Ranking”) in Private Colleges Category.',
    },
    {
        id: 'city10',
        url: 'https://images.app.goo.gl/gie9hUHf4prgP3NQ7',
        title: 'K. K. Wagh Institute Of Engineering Education & Research',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Karmaveer Kakasaheb Wagh Institute of Engineering Education & Research Nashik is the oldest engineering college in Nashik. It is a self-financed privately managed college recognized by AICTE adjudged in "A" grade by the Govt. of Maharashtra and affiliated to Pune University.',
    },
    {
        id: 'city11',
        url: 'https://images.app.goo.gl/mC3w7995o46qx44r5',
        title: 'Institute of Chemical Technology Mumbai (UDCT)',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Institute of Chemical Technology is a public deemed university in Mumbai India. The institute also has campuses at Bhubaneswar Odisha and Jalna. It is focused on training and research in the fields of chemical engineering chemical technology and pharmaceutical sciences.',
    },
    {
        id: 'city12',
        url: 'https://images.app.goo.gl/kwc6t4jrqGWhk7jH9',
        title: 'NMIMS College of Engineering (MPST&M)',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Mukesh Patel School of Technology Management and Engineering (MPSTME) Mumbai is a constituent school of SVKM\'s NMIMS (Deemed to be University) Mumbai. Established in 2006, the school has evolved into a leading technology and management institution. MPSTME Mumbai offers a range of undergraduate, postgraduate, and doctoral programs in various engineering and technology disciplines. The school focuses on providing quality education, fostering research and innovation, and nurturing industry-ready professionals. It is equipped with state-of-the-art facilities and has a strong emphasis on practical learning and industry collaboration.',
    },
    {
        id: 'city13',
        url: 'https://images.app.goo.gl/3khs6LRpFg8NWyce7',
        title: 'Sardar Patel Institute of Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sardar Patel Institute of Technology (SPIT) Mumbai is a premier engineering institution located in Mumbai, Maharashtra. Established in 1995, SPIT is affiliated with the University of Mumbai and is approved by the All India Council for Technical Education (AICTE). The institute offers undergraduate and postgraduate programs in various engineering disciplines. SPIT is known for its high academic standards, experienced faculty, and state-of-the-art infrastructure. The institute has a strong focus on research and development, industry collaboration, and holistic student development. It aims to produce competent and socially responsible engineers.',
    },
    {
        id: 'city14',
        url: 'https://images.app.goo.gl/Zv8Vo27uF7A8K7LN6',
        title: 'Vishwakarma Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vishwakarma Institute of Technology (VIT) Pune, established in 1983, is an autonomous institute affiliated with Savitribai Phule Pune University. It is approved by AICTE and accredited by NBA. VIT Pune offers a wide range of undergraduate, postgraduate, and doctoral programs in engineering and technology. The institute is known for its emphasis on research, innovation, and industry-oriented education. It provides state-of-the-art facilities, experienced faculty, and a vibrant campus environment. VIT Pune aims to produce skilled engineers who can contribute effectively to society and industry.',
    },
    {
        id: 'city15',
        url: 'https://images.app.goo.gl/KcJvHcQHeMshC3QB8',
        title: 'Shri Ramdeobaba College of Engineering and Management',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Shri Ramdeobaba College of Engineering and Management (RCOEM) is a private engineering college in Nagpur, Maharashtra. Established in 1984, it offers undergraduate and postgraduate programs in engineering and management. The college is known for its high academic standards, experienced faculty, and excellent infrastructure. RCOEM aims to produce competent professionals who can contribute effectively to the industry and society.',
    },
    {
        id: 'city16',
        url: 'https://images.app.goo.gl/dXHT9Kj6Y5bYXxsRA',
        title: 'Walchand College of Engineering',
        state: 'Maharashtra',
        city: 'Sangli',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Walchand College of Engineering (WCE) Sangli is an autonomous engineering education institution in Sangli, Maharashtra. Established in 1947, it is one of the oldest engineering colleges in India. WCE offers undergraduate, postgraduate, and doctoral programs in various engineering disciplines. The college is known for its strong academic curriculum, research initiatives, and industry collaborations.',
    },
    {
        id: 'city17',
        url: 'https://images.app.goo.gl/N8zHTcjkFqTcxMEr8',
        title: 'MIT College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'MIT College of Engineering (MITCOE) Pune is a prominent engineering college affiliated with Savitribai Phule Pune University. Established in 2001, MITCOE offers undergraduate and postgraduate programs in various engineering disciplines. The college focuses on providing quality education, fostering innovation, and promoting research. It is equipped with modern facilities and has a strong industry network.',
    },
    {
        id: 'city18',
        url: 'https://images.app.goo.gl/rWBRUoZkhYTfsYnX9',
        title: 'Sinhgad College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sinhgad College of Engineering (SCOE) Pune is a well-known engineering college established in 1996. It is affiliated with Savitribai Phule Pune University and offers undergraduate and postgraduate programs in engineering. SCOE is known for its comprehensive academic programs, experienced faculty, and strong emphasis on research and development. The college has a vibrant campus life and excellent infrastructure.',
    },
    {
        id: 'city19',
        url: 'https://images.app.goo.gl/ZcMKkAe6StNf1UXi6',
        title: 'Dr. D.Y. Patil Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Dr. D.Y. Patil Institute of Technology (DYPIET) Pune is a leading engineering college affiliated with Savitribai Phule Pune University. Established in 1998, it offers a range of undergraduate and postgraduate programs in engineering and technology. The institute is known for its academic excellence, research initiatives, and strong industry connections. DYPIET provides a supportive learning environment with state-of-the-art facilities.',
    },
    {
        id: 'city20',
        url: 'https://images.app.goo.gl/YfT7oXdhUNrQXdtf9',
        title: 'Rajiv Gandhi Institute of Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Rajiv Gandhi Institute of Technology (RGIT) Mumbai is an engineering college affiliated with the University of Mumbai. Established in 1992, it offers undergraduate and postgraduate programs in various engineering disciplines. RGIT is known for its quality education, experienced faculty, and modern infrastructure. The college aims to develop competent engineers through a blend of theoretical and practical learning.',
    },
    {
        id: 'city21',
        url: 'https://images.app.goo.gl/bdUewVPW9zRM8b4m7',
        title: 'Sardar Patel College of Engineering',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sardar Patel College of Engineering (SPCE) Mumbai is one of the oldest engineering colleges in India, established in 1962. It is affiliated with the University of Mumbai and offers undergraduate and postgraduate programs in engineering. SPCE is known for its academic excellence, experienced faculty, and strong research focus. The college has a rich legacy of producing skilled engineers who contribute significantly to the industry.',
    },
    {
        id: 'city22',
        url: 'https://images.app.goo.gl/WZK8x5HeBxKt5yQY9',
        title: 'Padmashree Dr. D.Y. Patil Institute of Engineering and Technology',
        state: 'Maharashtra',
        city: 'Pimpri',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Padmashree Dr. D.Y. Patil Institute of Engineering and Technology (DYPIET) Pimpri is a prestigious engineering college affiliated with Savitribai Phule Pune University. Established in 1998, it offers undergraduate and postgraduate programs in engineering. The institute is known for its academic rigor, research initiatives, and excellent infrastructure. DYPIET aims to provide a holistic education that fosters innovation and industry readiness.',
    },
    {
        id: 'city23',
        url: 'https://images.app.goo.gl/Z8U8qLeVXphYqUe38',
        title: 'Fr. Conceicao Rodrigues College of Engineering',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Fr. Conceicao Rodrigues College of Engineering (CRCE) Mumbai is an esteemed engineering college affiliated with the University of Mumbai. Established in 1984, it offers undergraduate and postgraduate programs in various engineering disciplines. CRCE is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college focuses on nurturing competent engineers through a blend of academics and practical exposure.',
    },
    {
        id: 'city24',
        url: 'https://images.app.goo.gl/H5U7yG4MkXnpEWsA9',
        title: 'AISSMS College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'All India Shri Shivaji Memorial Society\'s College of Engineering (AISSMS COE) Pune is an established engineering college affiliated with Savitribai Phule Pune University. Founded in 1992, it offers a range of undergraduate and postgraduate programs in engineering. AISSMS COE is known for its strong academic curriculum, experienced faculty, and modern facilities. The college aims to develop skilled engineers through innovative teaching methods and practical learning.',
    },
    {
        id: 'city25',
        url: 'https://images.app.goo.gl/tT6jv8mEts1phw4p6',
        title: 'Terna Engineering College',
        state: 'Maharashtra',
        city: 'Navi Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Terna Engineering College (TEC) Navi Mumbai is an engineering college affiliated with the University of Mumbai. Established in 1991, it offers undergraduate and postgraduate programs in various engineering disciplines. TEC is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college emphasizes practical learning and industry collaboration to develop competent engineers.',
    },
    {
        id: 'city26',
        url: 'https://images.app.goo.gl/qU7cXbP6dYpN5KfGA',
        title: 'G.H. Raisoni College of Engineering',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'G.H. Raisoni College of Engineering (GHRCE) Nagpur is a well-known engineering college affiliated with Rashtrasant Tukadoji Maharaj Nagpur University. Established in 1996, it offers a range of undergraduate and postgraduate programs in engineering. GHRCE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city27',
        url: 'https://images.app.goo.gl/PMD7HRqkG5JmHMzU9',
        title: 'Vishwakarma Institute of Information Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vishwakarma Institute of Information Technology (VIIT) Pune is an autonomous engineering college affiliated with Savitribai Phule Pune University. Established in 2002, it offers undergraduate and postgraduate programs in various engineering disciplines. VIIT is known for its focus on research, innovation, and industry-oriented education. The institute provides state-of-the-art facilities, experienced faculty, and a vibrant campus environment.',
    },
    {
        id: 'city28',
        url: 'https://images.app.goo.gl/rXdN2HnTbdPvc7vVA',
        title: 'Vidyalankar Institute of Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vidyalankar Institute of Technology (VIT) Mumbai is a premier engineering college affiliated with the University of Mumbai. Established in 1999, it offers undergraduate and postgraduate programs in various engineering disciplines. VIT is known for its high academic standards, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through a blend of theoretical and practical learning.',
    },
    {
        id: 'city29',
        url: 'https://images.app.goo.gl/M1h3R2YY8uG8phFZ8',
        title: 'Rajiv Gandhi College of Engineering and Research',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Rajiv Gandhi College of Engineering and Research (RGCER) Nagpur is an engineering college affiliated with Rashtrasant Tukadoji Maharaj Nagpur University. Established in 2008, it offers undergraduate and postgraduate programs in various engineering disciplines. RGCER is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college aims to develop skilled engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city30',
        url: 'https://images.app.goo.gl/2U3t1tZcP5XZp1rF9',
        title: 'Yeshwantrao Chavan College of Engineering',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Yeshwantrao Chavan College of Engineering (YCCE) Nagpur is an autonomous engineering college affiliated with Rashtrasant Tukadoji Maharaj Nagpur University. Established in 1984, it offers undergraduate and postgraduate programs in various engineering disciplines. YCCE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city31',
        url: 'https://images.app.goo.gl/jU9i9oG6dbdq3fYMA',
        title: 'VJTI',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Veermata Jijabai Technological Institute (VJTI) Mumbai is a premier engineering institute with a rich history dating back to 1887. It offers undergraduate, postgraduate, and doctoral programs in various engineering and technology disciplines. VJTI is known for its high academic standards, research excellence, and strong industry connections. The institute provides state-of-the-art facilities, experienced faculty, and a vibrant campus environment.',
    },
    {
        id: 'city32',
        url: 'https://images.app.goo.gl/8L4tZZfdtQyN9VjN6',
        title: 'Shri Sant Gajanan Maharaj College of Engineering',
        state: 'Maharashtra',
        city: 'Shegaon',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Shri Sant Gajanan Maharaj College of Engineering (SSGMCE) Shegaon is an engineering college affiliated with Sant Gadge Baba Amravati University. Established in 1983, it offers undergraduate and postgraduate programs in various engineering disciplines. SSGMCE is known for its quality education, experienced faculty, and excellent infrastructure. The college emphasizes practical learning and industry collaboration to develop competent engineers.',
    },
    {
        id: 'city33',
        url: 'https://images.app.goo.gl/dXZP8RUZQkV8rf9p8',
        title: 'Priyadarshini College of Engineering',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Priyadarshini College of Engineering (PCE) Nagpur is an engineering college affiliated with Rashtrasant Tukadoji Maharaj Nagpur University. Established in 1990, it offers undergraduate and postgraduate programs in various engineering disciplines. PCE is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college focuses on nurturing competent engineers through a blend of theoretical and practical learning.',
    },
    {
        id: 'city34',
        url: 'https://images.app.goo.gl/J68QZP3LFd8h5TDA8',
        title: 'Vishwakarma Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vishwakarma Institute of Technology (VIT) Pune is an autonomous institute affiliated with Savitribai Phule Pune University. Established in 1983, it offers a wide range of undergraduate, postgraduate, and doctoral programs in engineering and technology. VIT is known for its emphasis on research, innovation, and industry-oriented education. The institute provides state-of-the-art facilities, experienced faculty, and a vibrant campus environment.',
    },
    {
        id: 'city35',
        url: 'https://images.app.goo.gl/yz8KwC4HsFmDyrye6',
        title: 'JSPM Narhe Technical Campus',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'JSPM Narhe Technical Campus Pune is an engineering college affiliated with Savitribai Phule Pune University. Established in 2011, it offers undergraduate and postgraduate programs in various engineering disciplines. JSPM Narhe is known for its academic excellence, experienced faculty, and modern infrastructure. The college aims to develop competent engineers through innovative teaching methods and practical learning.',
    },
    {
        id: 'city36',
        url: 'https://images.app.goo.gl/gv6k4jhrFnZRtM7S9',
        title: 'Sandip Institute of Technology and Research Center',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sandip Institute of Technology and Research Center (SITRC) Nashik is an engineering college affiliated with Savitribai Phule Pune University. Established in 2008, it offers undergraduate and postgraduate programs in various engineering disciplines. SITRC is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college focuses on practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city37',
        url: 'https://images.app.goo.gl/2Hd8syRk6R9gGMZF7',
        title: 'MGM\'s College of Engineering and Technology',
        state: 'Maharashtra',
        city: 'Navi Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'MGM\'s College of Engineering and Technology (MGMCET) Navi Mumbai is an engineering college affiliated with the University of Mumbai. Established in 1982, it offers undergraduate and postgraduate programs in various engineering disciplines. MGMCET is known for its quality education, experienced faculty, and modern infrastructure. The college emphasizes practical learning and industry collaboration to develop competent engineers.',
    },
    {
        id: 'city38',
        url: 'https://images.app.goo.gl/2U3t1tZcP5XZp1rF9',
        title: 'Yeshwantrao Chavan College of Engineering',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Yeshwantrao Chavan College of Engineering (YCCE) Nagpur is an autonomous engineering college affiliated with Rashtrasant Tukadoji Maharaj Nagpur University. Established in 1984, it offers undergraduate and postgraduate programs in various engineering disciplines. YCCE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city39',
        url: 'https://images.app.goo.gl/hXfgJGzK5Rj1d9yS6',
        title: 'Sinhgad Institute of Technology and Science',
        state: 'Maharashtra',
        city: 'Narhe',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sinhgad Institute of Technology and Science (SITS) Narhe is an engineering college affiliated with Savitribai Phule Pune University. Established in 2008, it offers undergraduate and postgraduate programs in various engineering disciplines. SITS is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city40',
        url: 'https://images.app.goo.gl/7v6pHYQaE9cF3ys8A',
        title: 'Dr. D.Y. Patil School of Engineering and Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Dr. D.Y. Patil School of Engineering and Technology (DYPSOET) Pune is an engineering college affiliated with Savitribai Phule Pune University. Established in 2010, it offers undergraduate and postgraduate programs in various engineering disciplines. DYPSOET is known for its academic excellence, research initiatives, and strong industry connections. The college provides a supportive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city41',
        url: 'https://images.app.goo.gl/TcNwhecXqN63B1ZZ9',
        title: 'Sanjivani College of Engineering',
        state: 'Maharashtra',
        city: 'Kopargaon',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sanjivani College of Engineering (SCOE) Kopargaon is an engineering college affiliated with Savitribai Phule Pune University. Established in 1983, it offers undergraduate and postgraduate programs in various engineering disciplines. SCOE is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college emphasizes practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city42',
        url: 'https://images.app.goo.gl/J5Q9VMykeFQC9Y6V9',
        title: 'Bharti Vidyapeeth College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Bharati Vidyapeeth College of Engineering (BVCOE) Pune is an engineering college affiliated with Bharati Vidyapeeth Deemed University. Established in 1983, it offers undergraduate and postgraduate programs in various engineering disciplines. BVCOE is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on developing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city43',
        url: 'https://images.app.goo.gl/x14cV2jcdN3jtTzBA',
        title: 'Vidya Pratishthan\'s College of Engineering',
        state: 'Maharashtra',
        city: 'Baramati',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vidya Pratishthan\'s College of Engineering (VP COE) Baramati is an engineering college affiliated with Savitribai Phule Pune University. Established in 2000, it offers undergraduate and postgraduate programs in various engineering disciplines. VP COE is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college aims to produce competent engineers through a blend of theoretical and practical learning.',
    },
    {
        id: 'city44',
        url: 'https://images.app.goo.gl/dDJdfkA2Kop4NXue8',
        title: 'MIT Academy of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'MIT Academy of Engineering (MITAOE) Pune is an autonomous engineering college affiliated with Savitribai Phule Pune University. Established in 1999, it offers undergraduate and postgraduate programs in various engineering disciplines. MITAOE is known for its academic rigor, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city45',
        url: 'https://images.app.goo.gl/vhHRr9F5xeTXtgy57',
        title: 'NBN Sinhgad School of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'NBN Sinhgad School of Engineering (NBNSOE) Pune is an engineering college affiliated with Savitribai Phule Pune University. Established in 2011, it offers undergraduate and postgraduate programs in various engineering disciplines. NBNSOE is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city46',
        url: 'https://images.app.goo.gl/qwRJvK5erUM6gkXF6',
        title: 'Rajarshi Shahu College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Rajarshi Shahu College of Engineering (RSCOE) Pune is an autonomous engineering college affiliated with Savitribai Phule Pune University. Established in 2001, it offers undergraduate and postgraduate programs in various engineering disciplines. RSCOE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a supportive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city47',
        url: 'https://images.app.goo.gl/HJKNkK2kQcqB9tK77',
        title: 'Maharashtra Institute of Technology',
        state: 'Maharashtra',
        city: 'Aurangabad',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Maharashtra Institute of Technology (MIT) Aurangabad is an engineering college affiliated with Dr. Babasaheb Ambedkar Marathwada University. Established in 1982, it offers undergraduate and postgraduate programs in various engineering disciplines. MIT is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college focuses on developing competent engineers through innovative teaching methods and practical learning.',
    },
    {
        id: 'city48',
        url: 'https://images.app.goo.gl/BcyEEN7yMLUNEDqUA',
        title: 'Pune Vidyarthi Griha\'s College of Engineering and Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Pune Vidyarthi Griha\'s College of Engineering and Technology (PVGCOET) Pune is an engineering college affiliated with Savitribai Phule Pune University. Established in 1985, it offers undergraduate and postgraduate programs in various engineering disciplines. PVGCOET is known for its academic rigor, experienced faculty, and modern infrastructure. The college aims to produce competent engineers through a blend of theoretical and practical learning.',
    },
    {
        id: 'city49',
        url: 'https://images.app.goo.gl/jNftLHPchF9rz5jx9',
        title: 'Nagarjuna College of Engineering and Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Nagarjuna College of Engineering and Technology (NCET) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 2001, it offers undergraduate and postgraduate programs in various engineering disciplines. NCET is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college focuses on practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city50',
        url: 'https://images.app.goo.gl/t1H9iM7NhYGg5TyJ9',
        title: 'Sahyadri College of Engineering and Management',
        state: 'Karnataka',
        city: 'Mangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sahyadri College of Engineering and Management (SCEM) Mangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 2007, it offers undergraduate and postgraduate programs in various engineering disciplines. SCEM is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college emphasizes practical learning and industry collaboration to develop competent engineers.',
    },
    {
        id: 'city51',
        url: 'https://images.app.goo.gl/t1H9iM7NhYGg5TyJ9',
        title: 'KLE Technological University',
        state: 'Karnataka',
        city: 'Hubli',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'KLE Technological University (KLE Tech) Hubli, formerly known as BV Bhoomaraddi College of Engineering and Technology, is a private university established in 1947. It offers undergraduate, postgraduate, and doctoral programs in various engineering disciplines. KLE Tech is known for its academic excellence, research initiatives, and strong industry connections. The university provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city52',
        url: 'https://images.app.goo.gl/q8Q6opCKrJGX3p9D6',
        title: 'Acharya Institute of Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Acharya Institute of Technology (AIT) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 2000, it offers undergraduate and postgraduate programs in various engineering disciplines. AIT is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city53',
        url: 'https://images.app.goo.gl/2Ymv3pBLkXqVLUNa9',
        title: 'RNS Institute of Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'RNS Institute of Technology (RNSIT) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 2001, it offers undergraduate and postgraduate programs in various engineering disciplines. RNSIT is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college emphasizes practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city54',
        url: 'https://images.app.goo.gl/9JfG2TGzJ2KHdVjC6',
        title: 'The National Institute of Engineering',
        state: 'Karnataka',
        city: 'Mysore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'The National Institute of Engineering (NIE) Mysore is an engineering college affiliated with Visvesvaraya Technological University. Established in 1946, it offers undergraduate and postgraduate programs in various engineering disciplines. NIE is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city55',
        url: 'https://images.app.goo.gl/HvR7pXBB7B2yR8c56',
        title: 'BMS Institute of Technology and Management',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'BMS Institute of Technology and Management (BMSIT&M) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 2002, it offers undergraduate and postgraduate programs in various engineering disciplines. BMSIT&M is known for its academic excellence, experienced faculty, and modern infrastructure. The college emphasizes practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city56',
        url: 'https://images.app.goo.gl/fj2jF6Z6GzU2v3wz8',
        title: 'Sri Jayachamarajendra College of Engineering',
        state: 'Karnataka',
        city: 'Mysore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sri Jayachamarajendra College of Engineering (SJCE) Mysore is an autonomous engineering college affiliated with Visvesvaraya Technological University. Established in 1963, it offers undergraduate and postgraduate programs in various engineering disciplines. SJCE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city57',
        url: 'https://images.app.goo.gl/g6rSfbwX3tG9WStm8',
        title: 'Nitte Meenakshi Institute of Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Nitte Meenakshi Institute of Technology (NMIT) Bangalore is an autonomous engineering college affiliated with Visvesvaraya Technological University. Established in 2001, it offers undergraduate and postgraduate programs in various engineering disciplines. NMIT is known for its academic excellence, research initiatives, and strong industry connections. The college provides a supportive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city58',
        url: 'https://images.app.goo.gl/Jy3y8zDVe5SyFyx89',
        title: 'New Horizon College of Engineering',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'New Horizon College of Engineering (NHCE) Bangalore is an autonomous engineering college affiliated with Visvesvaraya Technological University. Established in 2001, it offers undergraduate and postgraduate programs in various engineering disciplines. NHCE is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on practical learning and industry collaboration to develop competent engineers.',
    },
    {
        id: 'city59',
        url: 'https://images.app.goo.gl/pgHP9JG9BDuGX8y86',
        title: 'Sir M. Visvesvaraya Institute of Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sir M. Visvesvaraya Institute of Technology (Sir MVIT) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 1986, it offers undergraduate and postgraduate programs in various engineering disciplines. Sir MVIT is known for its quality education, experienced faculty, and state-of-the-art infrastructure. The college emphasizes practical learning and industry collaboration to develop skilled engineers.',
    },
    {
        id: 'city60',
        url: 'https://images.app.goo.gl/V4EXUZrwWzF8nvPb7',
        title: 'JSS Academy of Technical Education',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'JSS Academy of Technical Education (JSSATE) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 1997, it offers undergraduate and postgraduate programs in various engineering disciplines. JSSATE is known for its academic excellence, experienced faculty, and modern infrastructure. The college focuses on nurturing competent engineers through innovative teaching methods and practical exposure.',
    },
    {
        id: 'city61',
        url: 'https://images.app.goo.gl/J8xN8XZbZXf8H4Mx6',
        title: 'Dayananda Sagar College of Engineering',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Dayananda Sagar College of Engineering (DSCE) Bangalore is an engineering college affiliated with Visvesvaraya Technological University. Established in 1979, it offers undergraduate and postgraduate programs in various engineering disciplines. DSCE is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city62',
        url: 'https://images.app.goo.gl/2bG9JvLdsJ5sNsw66',
        title: 'PES University',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'PES University Bangalore is a private university established in 1972. It offers undergraduate, postgraduate, and doctoral programs in various engineering and technology disciplines. PES University is known for its academic excellence, research initiatives, and strong industry connections. The university provides a supportive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city63',
        url: 'https://images.app.goo.gl/9jqPDtWVUPVBfA6d8',
        title: 'Ramaiah Institute of Technology',
        state: 'Karnataka',
        city: 'Bangalore',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Ramaiah Institute of Technology (RIT) Bangalore, formerly known as M.S. Ramaiah Institute of Technology, is an engineering college affiliated with Visvesvaraya Technological University. Established in 1962, it offers undergraduate and postgraduate programs in various engineering disciplines. RIT is known for its academic excellence, research initiatives, and strong industry connections. The college provides a conducive learning environment with modern facilities and experienced faculty.',
    },
    {
        id: 'city64',
        url: '', // Add image URL if available
        title: 'Sandip Institute of Engineering and Management',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sandip Institute of Engineering and Management, situated in Nashik, Maharashtra, is a prominent institution offering undergraduate and postgraduate programs in engineering and management disciplines. Established in [insert establishment year if available], the institute is affiliated with Savitribai Phule Pune University (SPPU) and approved by the All India Council for Technical Education (AICTE). With a focus on holistic development, industry-oriented curriculum, and experiential learning, Sandip Institute of Engineering and Management aims to groom future leaders and innovators in engineering and management domains.'
    },
    {
        id: 'city65',
        url: ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_GRJfKx6ceLXHEcfTbfR2Alsl8IbtEhUdM3i9ep088A&s ',
        title: 'Matoshri College of Engineering and Research Centre',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Matoshri College of Engineering and Research Centre, located in Nashik, Maharashtra, is dedicated to providing quality education in engineering and technology. Established in [insert establishment year if available], the college offers undergraduate and postgraduate programs in various engineering disciplines. Affiliated with Savitribai Phule Pune University (SPPU) and approved by the All India Council for Technical Education (AICTE), Matoshri College of Engineering and Research Centre focuses on imparting practical skills, fostering innovation, and promoting research and development activities among its students.'
    },
    {
        id: 'city66',
        url: ' https://mvp.edu.in/mvpsite/wp-content/uploads/2023/07/3.jpg ',
        title: 'MVP Samaj\'s College of Engineering',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'MVP Samaj\'s College of Engineering, located in Nashik, Maharashtra, is committed to providing quality education in engineering and technology. Established in [insert establishment year if available], the college offers undergraduate and postgraduate programs in various engineering disciplines. Affiliated with Savitribai Phule Pune University (SPPU) and approved by the All India Council for Technical Education (AICTE), MVP Samaj\'s College of Engineering emphasizes academic excellence, industry exposure, and holistic development to prepare students for successful careers in their chosen fields.'
    },
    {
        id: 'city67',
        url: 'https://images.shiksha.com/mediadata/images/1490770158phpRnBdO3.jpeg',
        title: 'Symbiosis Institute of Technology',
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Symbiosis Institute of Technology (SIT), located in Pune, Maharashtra, is a premier technical institution offering undergraduate and postgraduate programs in engineering and technology. Established in 2008, SIT is affiliated with Symbiosis International (Deemed University) and approved by the All India Council for Technical Education (AICTE). With a focus on innovation, research, and industry collaboration, Symbiosis Institute of Technology aims to nurture technologically adept professionals who can thrive in a globalized environment.'
    },
    {
        id: 'city68',
        url: ' https://images.collegedunia.com/public/college_data/images/appImage/1623662091NewPicture.png', 
        title: " Nashik's N.B. Naavle Singhad College of Engineering",
        state: 'Maharashtra',
        city: 'Nashik',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'N.B. Naavle Singhad College of Engineering, under the aegis located in Nashik, Maharashtra, is dedicated to providing quality education in engineering and technology. Established in [insert establishment year if available], the college offers undergraduate and postgraduate programs in various engineering disciplines. Affiliated with Savitribai Phule Pune University (SPPU) and approved by the All India Council for Technical Education (AICTE), N.B. Naavle Singhad College of Engineering focuses on academic rigor, industry relevance, and holistic development to groom competent professionals.'
    },
    {
        id: 'city69',
        url: 'https://images.collegedunia.com/public/college_data/images/appImage/28960_JCET_NEW.jpg',
        title: 'Jagadamba College of Engineering and Technology',
        state: 'Maharashtra',
        city: 'Yavatmal',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Jagadamba College of Engineering and Technology, located in Yavatmal, Maharashtra, is a leading institution offering undergraduate and postgraduate programs in engineering and technology. Established in [insert establishment year if available], the college is affiliated with Sant Gadge Baba Amravati University and approved by the All India Council for Technical'
    },
    {
        id: 'city70', 
        url: 'https://emango.s3.amazonaws.com/media/cache/43/e3/43e388812fe854595bc95c4b61ddc5b9.jpg',
        title: 'Maharashtra Academy of Engineering',
        state: 'Maharashtra',
        city: 'Alandi',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: "MIT Academy of Engineering is an autonomous engineering college located on Pune - Alandi Road. It is an integral part of MAEER's MIT Pune Group of Institutions, established by the honorable Prof. Dr. Vishwanath D. Karad, Founder and Executive President of MIT Group. The institute offers B.Tech and M.Tech courses in trending technologies and specializations. The engineering courses have been approved by AICTE and affiliated with Savitribai Phule Pune University.",
    },
    {
        id: 'city71', 
        url: ' https://images.shiksha.com/mediadata/images/1402986669phpOZV1AN.jpeg',
        title: 'Dr. D. Y. Patil Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ' Dr. D. Y. Patil Vidyapeeth (DPU), Pune was established in 2003.'
    },
    {
        id: 'city72',
        url: 'https://www.collegebatch.com/static/clg-gallery/dwarkadas-j-sanghvi-college-of-engineering-mumbai-213171.jpg',
        title: 'Shri Vile Parle Kelavani Mandal`s  Dwarkadas J. Sanghvi College of Engineering',
        state: 'Maharashtra',
        city: 'Mumbai Surburban',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Shri Vile Parle Kelavani Mandal is a Public Charitable Trust registered under the Society’s Registration Act and Bombay Public Trust Act. From its humble beginnings in 1934, when it took over the Rashtriya Shala, a school established in 1921 in the wake of the National Movement, the Mandal today has grown into a big educational complex imparting high-level education to more than 50,000 students. The ethos of the Mandal, is marked by patriotic fervor, selfless service and a spirit of indigenous enterprise. These values permeate all the institutions set up by the Mandal and are the guiding principles for all of them. After beginning its journey in the early 1930s SVKM has blossomed into an educational colossus that has attained national recognition in multiple streams of higher education. With a strong guiding philosophy of providing education to all levels of the student community along with creating a feeling of bonding and commitment amongst academic and nonacademic employees. SVKM has mastered the art of being able to transform itself into a close knit family and at the same time help its students to attain all-round development, be employable and achieve success.'
    },
    {
        id: 'city73',
        url: 'https://5.imimg.com/data5/SELLER/Default/2022/8/EZ/KB/EO/144387079/thakur-college-of-engineering-and-technology.jpg',
        title: 'Thakur College of Engineering & Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Thakur College of Engineering & Technology (TCET), a Graded Autonomous Linguistic Minority Institute, was established in AY 2001-02 with a clear objective of providing Quality Technical Education in tune with international standards and contemporary global requirements. The Institute is recognized by All India Council for Technical Education (AICTE) & Government of Maharashtra and is affiliated to the University of Mumbai (UOM). It has been conferred Autonomous Status by University Grant Commission (UGC) for 10 years w.e.f. A.Y. 2019-20 to A.Y. 2028-29.'
    },
    {
        id: 'city74',
        url: 'https://images.collegedunia.com/public/college_data/images/appImage/14564_PCCE_New.jpg?h=260&w=360&mode=crop',
        title: 'Pimpiri Chinchwad College of Engineering',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city75',
        url: 'https://img.jagranjosh.com/images/2024/April/1842024/MKSSSs-Cummins-College-of-Engineering-for-Women-Pune-campus1.jpg',
        title: 'Maharshi Karve Stree Shikshan Samstha’s Cummin’s College of Engineering for Women',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'MKSSS\'s Cummins College of Engineering for Women (CCOEW) is an Autonomous engineering college in Pune, Maharashtra, India established in 1991 and run by the Maharshi Karve Stree Shikshan Samstha.'
    },
    {
        id: 'city76',
        url: 'https://i.ytimg.com/vi/BEjLcQGDvps/maxresdefault.jpg',
        title: 'Sardar Patel College of Engineering',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Bharatiya Vidya Bhavan\'s Sardar Patel College of Engineering (SPCE) was established in 1962 as a Government Aided Engineering College. It was started with three conventional courses. viz., Civil, Electrical and Mechanical with an intake of 40 in each branch which was subsequently increased to 60. The institute is permanently affiliated to University of Mumbai. Over the last 50 years the college has gained an excellent reputation in the field of Technical Education. S.P.C.E. Grade "A" rating engineering college from Govt. of Maharashtra has maintained a proud tradition of excellent academic records by securing high ranks, gold medals and other awards in the University Exams. The college has produced many graduates and Post-graduate Engineers, many of our past students are now leaders in their professions. S.P.C.E. Alumni can be found in all public and private sector organizations operating in diverse fields, often holding senior and key positions in the organization. The institute is a recognized PhD and QIP center. It has become autonomous since 2010 and is one of the TEQIP- II institutes.'
    },
    {
        id: 'city77',
        url: 'https://www.vit.edu/media/k2/items/src/1d11e5ebeed3c42540f69555bbe34fb8.jpg',
        title: 'Bansilal Ramnath Agarwal Charitable Trust`s Vishwakarama Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Vishwakarma Institute of Technology is an autonomous institute in Pune, Maharashtra, India. Established in 1983, the institute is affiliated with the Savitribai Phule Pune University and run by the Bansilal Ramnath Agarwal Charitable Trust.'
    },
    {
        id: 'city78',
        url: 'https://emango.s3.amazonaws.com/media/cache/70/49/7049a98a196338de769e6a9b417ef53c.jpg',
        title: 'Dr. Vishwanath Karad MIT World Peace University',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Established in 2017, MIT World Peace University is a private university located in Kothrud, Pune. With 150+ programs in Management, Engineering, Design, and more, MIT-WPU consistently ranks among the country\'s top universities MIT Pune is a part of MAEER’s MIT Group of Institutions. MIT World Peace University.'
    },
    {
        id: 'city79',
        url: 'https://www.collegebatch.com/static/clg-gallery/rashtrasant-tukadoji-maharaj-nagpur-university-nagpur-215482.jpg',
        title: 'The Rashtrasant Tukadoji Maharaj Nagpur University',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU), formerly Nagpur University, is a public state university located in Nagpur, Maharashtra. It is one of India\'s oldest universities, as well as the second oldest in Maharashtra. It is named after Rashtrasant Tukdoji Maharaj, a spiritual leader, orator, and musician from Vidarbha. The university is a member of the Association of Indian Universities and the Association of Commonwealth Universities.'
    },
    {
        id: 'city80',
        url: 'https://mca.spit.ac.in/wp-content/uploads/2022/12/20221212_120147-scaled-e1670904222265-1024x463.jpg',
        title: 'Bharatiya Vidya Bhavan`s Sardar Patel Institute of Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Sardar Patel Institute of Technology is one of India’s top-rated colleges for B.E. / B.Tech, M.E./M.Tech, MCA programs. The institute was established in 1962 and is located in Mumbai, Maharashtra. As of now, the institute comprises a total of 5 specialization courses Information Technology, Electronics Engineering, Electronics & Communication Engineering, Computer Science Engineering, Artificial Intelligence & Machine Learning while the number of seats available in the current scenario is 696. Additionally, the institute revolves around the Engineering, IT & Software studies stream and offers courses in Full-Time mode. Moreover, it also offers Degree programs, giving students a variety of credentials to choose from. The institute is approved by AICTE and they provides a variety of UG and PG programs at a reasonable fee, ranging from INR 292,172-608,696.'
    },
    {
        id: 'city81',
        url: 'https://images.shiksha.com/mediadata/images/1670480521phpBHRBwz.jpeg',
        title: 'SVKM`s Narsee Monjee Institute of Management Studies',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'Narsee Monjee is ranked 101-150 by NIRF 2023 under the Engineering category, 21 under the Management category by NIRF 2023, and 11 by NIRF 2023 under the Pharmacy category. NMIMS University is famous for its flagship MBA and BTech courses. Narsee Monjee Institute of Management Studies has a strong industry interface and corporate relationships with over 1,348 companies. SVKM NMIMS follows an Assurance of Learning (AoL) or Outcome-Based Education (OBE). At present, the university has more than 17,000 full-time students and over 750 full-time faculty members.'
    },
    {
        id: 'city82',
        url: 'https://images.collegedunia.com/public/college_data/images/appImage/25693_X20.jpg',
        title: 'Defence Institute of Advanced Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: 'The Defence Institute of Advanced Technology (DIAT) is the premier engineering training institute under the Department of Defence Research & Development, Ministry of Defence, and Government of India. DIAT (DU) specializes in training officers from Defence Research Organizations, IOFS (Indian Ordnance Factories), Defence PSUs (like Hindustan Aeronautics Limited, Bharat Electronics, Bharat Dynamics Limited), ship building agencies (like Garden Reach Shipbuilders & Engineers, Cochin and Goa Shipyards), Mazagon Dock Shipbuilders, armed forces of friendly countries (like Sri Lanka and Afghanistan,), and other central and state governmental agencies.'
    },
    {
        id: 'city83',
        url: '',
        title: 'Maharashtra Institute of Technology',
        state: 'Maharashtra',
        city: 'Pune',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city84',
        url: '',
        title: 'G. H. Raisoni College of Engineering',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city85',
        url: '',
        title: 'National Institute of Industrial Engineering',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city86',
        url: '',
        title: 'Institute of Chemical Technology',
        state: 'Maharashtra',
        city: 'Mumbai',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city87',
        url: '',
        title: 'Shri Guru Gobind Singhji Institute Of Engineering And Technology',
        state: 'Maharashtra',
        city: 'Nanded',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    },
    {
        id: 'city88',
        url: '',
        title: 'Shri Ramdeobaba College Of Engineering And Management',
        state: 'Maharashtra',
        city: 'Nagpur',
        AdmissionProcess: '',
        Coursesoffer: '',
        FeeStructure: '',
        Placement: '',
        Cutoff: '',
        detail: ''
    }
    
];
